@startuml
class renderer.SkillButtonRenderer {
+ {static} double BTN_Y
+ {static} double BTN_R
+ {static} double[] P1_BTN_X
+ {static} double[] P2_BTN_X
- {static} int ABILITY_IDX
- {static} Color[] BASE_COLORS
- {static} String[] ATK_NAMES
- GraphicsContext gc
- Controller controller
+ <<Create>> SkillButtonRenderer(GraphicsContext,Controller)
+ void draw()
- void drawPlayerButtons(double[],boolean)
}


class attack.NormalAttack {
+ void attack(BasePlayer)
+ String getName()
+ int getCooldown()
}

class renderer.GameRenderer {
- GraphicsContext gc
- Controller controller
- BasePlayer p1
- BasePlayer p2
- HudRenderer hud
- SkillButtonRenderer buttons
- EffectRenderer effects
- ProjectileRenderer projectileRenderer
- String lastResult
- int resultTimer
- Image backgroundImage
- {static} double GROUND_Y
+ <<Create>> GameRenderer(GraphicsContext,Controller,BasePlayer,BasePlayer)
+ void onResult(String)
+ void reset()
+ void render()
- void drawBackground()
- void drawResultFlash()
- double charX(int)
}


class application.HandleInput {
- Scene scene
- Controller controller
+ <<Create>> HandleInput(Scene,Controller)
+ void process()
- void handleClick(double,double)
}


class application.CharacterSelectScene {
- {static} double CARD_W
- {static} double CARD_H
- {static} double SPRITE_SIZE
- BasePlayer p1Selected
- BasePlayer p2Selected
- Button p1DogBtn
- Button fightBtn
+ Scene build(Runnable)
- VBox buildPlayerPanel(boolean)
- Button buildCharCard(boolean,boolean)
- void selectChar(boolean,boolean)
+ BasePlayer getP1()
+ BasePlayer getP2()
- {static} String cardUnselected()
- {static} String cardSelected(boolean)
- {static} String fightDisabledStyle()
- {static} String fightReadyStyle()
}


class renderer.ProjectileRenderer {
- GraphicsContext gc
- Controller controller
+ <<Create>> ProjectileRenderer(GraphicsContext,Controller)
+ void draw()
- void drawAiming(Projectile)
- void drawAimArrow(double,double,double,double)
- void drawFlying(Projectile)
}


class character.CatPlayer {
- boolean perfectAimReady
+ <<Create>> CatPlayer()
+ String getSpritePath()
+ String getName()
+ String getAbilityLabel()
+ AbilityType getAbilityType()
+ BasePlayer recreate()
+ void ability()
+ boolean isPerfectAimReady()
+ void resetAbilityEffect()
}


enum character.AbilityType {
+  HEAL
+  AIM
}

class character.DogPlayer {
+ <<Create>> DogPlayer()
+ String getSpritePath()
+ String getName()
+ String getAbilityLabel()
+ AbilityType getAbilityType()
+ BasePlayer recreate()
+ void ability()
}

class game.Projectile {
- State state
- double x
- double angle
- int angleDir
- boolean hit
- boolean player1Turn
- List<double[]> trail
- double launchXOffset
- double targetXOffset
- boolean angleLocked
+ {static} double LAUNCH_SPEED
+ {static} double GRAVITY
+ {static} double MIN_ANGLE
+ {static} double MAX_ANGLE
+ {static} double ANGLE_SPEED
- {static} int TRAIL_MAX
+ {static} double GROUND_Y
+ {static} double P1_START_X
+ {static} double P1_START_Y
+ {static} double P2_START_X
+ {static} double P2_START_Y
+ {static} double P1_BOX_X1
+ {static} double P1_BOX_X2
+ {static} double P2_BOX_X1
+ {static} double P2_BOX_X2
+ {static} double BOX_Y1
+ {static} double BOX_Y2
+ void startAiming(boolean)
+ void fire()
+ void update()
+ double[][] getTrajectoryPoints(int)
+ void reset()
+ void setLaunchOffset(double)
+ void setTargetOffset(double)
+ void setLockedAngle(double)
+ void clearAngleLock()
+ double getLaunchXOffset()
+ boolean isAngleLocked()
+ State getState()
+ boolean isHit()
+ double getX()
+ double getY()
+ double getAngle()
+ boolean isPlayer1Turn()
+ List<double[]> getTrail()
}


enum game.State {
+  IDLE
+  AIMING
+  FLYING
}

abstract class attack.BaseAttack {
+ void attack(BasePlayer)
}

class attack.IceAttack {
+ {static} int COOLDOWN
+ String getName()
+ int getCooldown()
}


interface attack.Attackable {
~ void attack(BasePlayer)
~ String getName()
~ int getCooldown()
}

class renderer.HudRenderer {
- {static} double PANEL_W
- {static} double PANEL_H
- {static} double P2_PANEL_X
- {static} double BAR_INN_W
- GraphicsContext gc
- Controller controller
- BasePlayer p1
- BasePlayer p2
+ <<Create>> HudRenderer(GraphicsContext,Controller,BasePlayer,BasePlayer)
+ void draw()
- void drawHpBars()
- void drawTurnIndicator()
- {static} Color hpColor(double)
}


abstract class character.BasePlayer {
- int maxHp
- int hp
- Image sprite
# <<Create>> BasePlayer(int,int)
+ {abstract}void ability()
+ {abstract}String getName()
+ {abstract}String getAbilityLabel()
+ {abstract}AbilityType getAbilityType()
+ {abstract}String getSpritePath()
+ {abstract}BasePlayer recreate()
+ boolean isPerfectAimReady()
+ void resetAbilityEffect()
+ Image getSprite()
+ int getHp()
+ int getMaxHp()
+ void setHp(int)
+ void decreaseHp(int)
}


class renderer.EffectRenderer {
- {static} double GROUND_Y
- GraphicsContext gc
- Controller controller
- List<Particle> fireParticles
- List<Particle> iceParticles
- List<Particle> windParticles
+ <<Create>> EffectRenderer(GraphicsContext,Controller)
+ void reset()
+ void draw()
- void drawStatusBadges()
- void drawFireGlow()
- void emitFireParticles()
- void drawIceEffect()
- void emitIceParticles()
- void drawWindOverlay()
- void emitWindParticles()
- void updateAndDrawParticles()
- double charX(int)
}


class renderer.EffectRenderer$Particle {
~ double x
~ double maxLife
~ <<Create>> Particle(double,double,double,double,double)
~ boolean isDead()
~ double lifeRatio()
}


class application.Main {
- Stage window
- Scene menuScene
- BasePlayer p1
- BasePlayer p2
- AnimationTimer timer
- Controller controller
- GameRenderer renderer
+ void start(Stage)
- Scene buildMenuScene()
- {static} Button buildMenuButton(String,String)
- void showCharacterSelect()
- void startGame()
- Scene buildEndScene(String)
- {static} Button buildEndButton(String,String)
+ {static} void main(String[])
}


class attack.WindAttack {
+ {static} int COOLDOWN
+ String getName()
+ int getCooldown()
}


class attack.FireAttack {
+ {static} int COOLDOWN
+ String getName()
+ int getCooldown()
}


class game.Controller {
- BasePlayer p1
- BasePlayer p2
- boolean player1Turn
- Projectile projectile
- String projectileResult
- Attackable selectedAttack
- int burnTargetPlayer
- int burnTicksLeft
- int burnFrameTimer
+ {static} int BURN_TICKS
+ {static} int BURN_FRAMES_PER_TICK
- int frozenPlayer
- int frozenDisplayTimer
+ {static} int FROZEN_DISPLAY_FRAMES
- Map<String,int[]> cooldowns
+ {static} int WIND_TURNS
- int windTargetPlayer
- int windTurnsLeft
- int windFrameCounter
+ {static} int ABILITY_COOLDOWN
- int[] abilityCooldown
+ <<Create>> Controller(BasePlayer,BasePlayer)
+ boolean isCurrentPlayerFrozen()
+ void selectAttack(Attackable)
+ void handleSpacebar()
- void applySelectedAttack()
+ void update()
- void switchTurn()
+ void handleAbility()
- double calculatePerfectAngle()
+ double getWindXOffset(int)
+ String getSelectedAttackName()
+ AbilityType getAbilityType(boolean)
+ int getBurnTargetPlayer()
+ int getBurnTicksLeft()
+ int getBurnFrameTimer()
+ int getFrozenPlayer()
+ int getFrozenDisplayTimer()
+ Projectile getProjectile()
+ boolean isPlayer1Turn()
+ int getFireCooldown(boolean)
+ int getIceCooldown(boolean)
+ int getWindCooldown(boolean)
+ int getWindTargetPlayer()
+ int getWindTurnsLeft()
+ int getAbilityCooldown(boolean)
- int getCooldown(String,boolean)
+ String getAbilityLabel(boolean)
+ String getAndClearProjectileResult()
}




attack.BaseAttack <|-- attack.NormalAttack
character.BasePlayer <|-- character.CatPlayer
character.BasePlayer <|-- character.DogPlayer
attack.Attackable <|.. attack.BaseAttack
attack.BaseAttack <|-- attack.IceAttack
renderer.EffectRenderer +.. renderer.EffectRenderer$Particle
javafx.application.Application <|-- application.Main
attack.BaseAttack <|-- attack.WindAttack
attack.BaseAttack <|-- attack.FireAttack
@enduml