@startuml
class renderer.SkillButtonRenderer {
+ {static} double BTN_Y
+ {static} double BTN_R
+ {static} double[] P1_BTN_X
+ {static} double[] P2_BTN_X
- {static} int ABILITY_IDX
- {static} Color[] BASE_COLORS
- {static} String[] ATK_NAMES
- GraphicsContext gc
- Controller controller
+ <<Create>> SkillButtonRenderer(GraphicsContext,Controller)
+ void draw()
- void drawPlayerButtons(double[],boolean)
}


class application.scene.StartScene {
+ ImageView bg
+ Scene build()
- {static} Button buildMenuButton(String,String)
}


class attack.AttackTest {
- DogPlayer target
~ void setUp()
~ void testNormalAttackDealsOneDamage()
~ void testNormalAttackStacksWithMultipleHits()
~ void testNormalAttackCanReduceHpToZero()
~ void testFireAttackDealsNoDirectDamage()
~ void testIceAttackDealsNoDirectDamage()
~ void testWindAttackDealsNoDirectDamage()
}


class renderer.ProjectileRenderer {
- GraphicsContext gc
- Controller controller
+ <<Create>> ProjectileRenderer(GraphicsContext,Controller)
+ void draw()
- void drawAiming(Projectile)
- void drawAimArrow(double,double,double,double)
- void drawFlying(Projectile)
}


class application.scene.EndScene {
- BasePlayer p1
- BasePlayer p2
+ Scene buildEndScene(String,BasePlayer,BasePlayer)
- {static} Button buildEndButton(String,String)
}


class game.ProjectileTest {
- Projectile proj
~ void setUp()
~ void testInitialStateIsIdle()
~ void testStartAimingTransitionsToAiming()
~ void testFireTransitionsToFlying()
~ void testFireFromIdleDoesNothing()
~ void testResetReturnsToIdle()
~ void testResetClearsTrail()
~ void testResetClearsHitFlag()
~ void testP1LaunchX()
~ void testP2LaunchX()
~ void testLaunchOffsetShiftsP1StartX()
~ void testP1MovesRight()
~ void testP2MovesLeft()
~ void testAngleOscillatesWhileAiming()
~ void testAngleLockFreezesAngle()
~ void testIsAngleLockedAfterSet()
~ void testClearAngleLockUnlocks()
~ void testP1HitsP2AtFifteenDegrees()
~ void testP2HitsP1AtFifteenDegrees()
~ void testP1MissesAtMinimumAngle()
~ void testTrailGrowsWhileFlying()
~ void testGroundYConstant()
~ void testHitBoxYAlignedWithGround()
~ void testLaunchYAlignedWithGround()
~ void testTrajectoryPointsHaveCorrectCount()
~ void testTrajectoryPointsAreForwardForP1()
}


enum character.AbilityType {
+  HEAL
+  AIM
}

class renderer.HudRenderer {
- {static} double PANEL_W
- {static} double PANEL_H
- {static} double P2_PANEL_X
- {static} double P1_PANEL_X
- {static} double BAR_INN_W
- GraphicsContext gc
- Controller controller
- BasePlayer p1
- BasePlayer p2
+ <<Create>> HudRenderer(GraphicsContext,Controller,BasePlayer,BasePlayer)
+ void draw()
- void updateHpBars()
- void drawTurnIndicator()
- {static} Color hpColor(double)
}


class application.scene.GamePlayScene {
- AnimationTimer timer
- Controller controller
- GameRenderer renderer
- BasePlayer p1
- BasePlayer p2
+ Scene startGame(BasePlayer,BasePlayer)
}


class renderer.EffectRenderer {
- {static} double GROUND_Y
- GraphicsContext gc
- Controller controller
- List<Particle> fireParticles
- List<Particle> iceParticles
- List<Particle> windParticles
+ <<Create>> EffectRenderer(GraphicsContext,Controller)
+ void reset()
+ void draw()
- void drawStatusBadges()
- void drawFireGlow()
- void emitFireParticles()
- void drawIceEffect()
- void emitIceParticles()
- void drawWindOverlay()
- void emitWindParticles()
- void updateAndDrawParticles()
- double charX(int)
}


class renderer.EffectRenderer$Particle {
~ double x
~ double maxLife
~ <<Create>> Particle(double,double,double,double,double)
~ boolean isDead()
~ double lifeRatio()
}


class application.Main {
+ {static} Stage window
+ void start(Stage)
+ {static} void main(String[])
}


class game.ControllerTest {
- DogPlayer p1
- DogPlayer p2
- Controller controller
~ void setUp()
- String fireAndWait(Attackable,double,int)
~ void testInitiallyP1Turn()
~ void testProjectileInitiallyIdle()
~ void testWindXOffsetZeroInitially()
~ void testNoBurnInitially()
~ void testNotFrozenInitially()
~ void testSpacebarWithoutAttackDoesNothing()
~ void testFirstSpacebarStartsAiming()
~ void testSecondSpacebarFires()
~ void testTurnSwitchesAfterHit()
~ void testTurnSwitchesAfterMiss()
~ void testResultStringContainsHitOnHit()
~ void testResultStringContainsMissedOnMiss()
~ void testNormalHitDealsDamageToP2()
~ void testMissDealsNoDamage()
~ void testFireHitSetsBurnOnP2()
~ void testFireCooldownSetAfterHit()
~ void testBurnTickDealsDamage()
~ void testBurnTicksDecrementAfterEachTick()
~ void testIceHitFreezesP2()
~ void testIceHitDealsDamageToP2()
~ void testIceCooldownSetAfterHit()
~ void testFrozenPlayerTurnIsAutoSkipped()
~ void testWindHitSetsWindOnP2()
~ void testWindHitDealsDamageToP2()
~ void testWindCooldownSetAfterHit()
~ void testWindXOffsetNonZeroAfterEffect()
~ void testFireCooldownDecrementsAfterOpponentTurn()
~ void testIceIsRejectedWhileOnCooldown()
~ void testDogAbilityHeals()
~ void testDogAbilitySwitchesTurn()
~ void testDogAbilityCooldownSet()
~ void testCatAbilityLocksAngle()
~ void testCatAbilityDoesNotSwitchTurn()
~ void testAbilityLabelForDogPlayer()
~ void testAbilityLabelForCatPlayer()
~ void testMixedAbilityLabels()
}


class character.DogPlayerTest {
- DogPlayer dog
~ void setUp()
~ void testName()
~ void testAbilityLabel()
~ void testSpritePath()
~ void testInitialHp()
~ void testMaxHp()
~ void testDecreaseHp()
~ void testSetHp()
~ void testHealIncreasesHpByOne()
~ void testHealDoesNotExceedMaxHp()
~ void testNotPerfectAimReady()
~ void testResetAbilityEffectDoesNothing()
}


class attack.NormalAttack {
+ void attack(BasePlayer)
+ String getName()
+ int getCooldown()
}

class renderer.GameRenderer {
- GraphicsContext gc
- Controller controller
- BasePlayer p1
- BasePlayer p2
- HudRenderer hud
- SkillButtonRenderer buttons
- EffectRenderer effects
- ProjectileRenderer projectileRenderer
- String lastResult
- int resultTimer
- Image backgroundImage
- {static} double GROUND_Y
+ <<Create>> GameRenderer(GraphicsContext,Controller,BasePlayer,BasePlayer)
+ void onResult(String)
+ void reset()
+ void render()
- void drawBackground()
- void drawResultFlash()
- double charX(int)
}


class application.HandleInput {
- Scene scene
- Controller controller
+ <<Create>> HandleInput(Scene,Controller)
+ void process()
- void handleClick(double,double)
}


class character.CatPlayerTest {
- CatPlayer cat
~ void setUp()
~ void testName()
~ void testAbilityLabel()
~ void testSpritePath()
~ void testInitialHp()
~ void testMaxHp()
~ void testDecreaseHp()
~ void testSetHp()
~ void testAbilitySetsPerfectAimReady()
~ void testResetAbilityEffectClearsPerfectAim()
~ void testAbilityDoesNotChangeHp()
}


class application.scene.CharacterSelectScene {
- {static} double CARD_W
- {static} double CARD_H
- {static} double SPRITE_SIZE
- BasePlayer p1Selected
- BasePlayer p2Selected
- Button p1DogBtn
- Button fightBtn
+ Scene build()
- VBox buildPlayerPanel(boolean)
- Button buildCharCard(boolean,boolean)
- void selectChar(boolean,boolean)
+ BasePlayer getP1()
+ BasePlayer getP2()
- {static} String cardUnselected()
- {static} String cardSelected(boolean)
- {static} String fightDisabledStyle()
- {static} String fightReadyStyle()
}


class character.CatPlayer {
- boolean perfectAimReady
+ <<Create>> CatPlayer()
+ String getSpritePath()
+ String getName()
+ String getAbilityLabel()
+ AbilityType getAbilityType()
+ BasePlayer recreate()
+ void ability()
+ boolean isPerfectAimReady()
+ void resetAbilityEffect()
}


class character.DogPlayer {
+ <<Create>> DogPlayer()
+ String getSpritePath()
+ String getName()
+ String getAbilityLabel()
+ AbilityType getAbilityType()
+ BasePlayer recreate()
+ void ability()
}

class game.Projectile {
- State state
- double x
- double angle
- int angleDir
- boolean hit
- boolean player1Turn
- List<double[]> trail
- double launchXOffset
- double targetXOffset
- boolean angleLocked
+ {static} double LAUNCH_SPEED
+ {static} double GRAVITY
+ {static} double MIN_ANGLE
+ {static} double MAX_ANGLE
+ {static} double ANGLE_SPEED
- {static} int TRAIL_MAX
+ {static} double GROUND_Y
+ {static} double P1_START_X
+ {static} double P1_START_Y
+ {static} double P2_START_X
+ {static} double P2_START_Y
+ {static} double P1_BOX_X1
+ {static} double P1_BOX_X2
+ {static} double P2_BOX_X1
+ {static} double P2_BOX_X2
+ {static} double BOX_Y1
+ {static} double BOX_Y2
+ void startAiming(boolean)
+ void fire()
+ void update()
+ double[][] getTrajectoryPoints(int)
+ void reset()
+ void setLaunchOffset(double)
+ void setTargetOffset(double)
+ void setLockedAngle(double)
+ void clearAngleLock()
+ double getLaunchXOffset()
+ boolean isAngleLocked()
+ State getState()
+ boolean isHit()
+ double getX()
+ double getY()
+ double getAngle()
+ boolean isPlayer1Turn()
+ List<double[]> getTrail()
}


enum game.State {
+  IDLE
+  AIMING
+  FLYING
}

class attack.IceAttack {
+ {static} int COOLDOWN
+ String getName()
+ int getCooldown()
}


abstract class attack.BaseAttack {
+ void attack(BasePlayer)
}

interface attack.Attackable {
~ void attack(BasePlayer)
~ String getName()
~ int getCooldown()
}

abstract class character.BasePlayer {
- int maxHp
- int hp
- Image sprite
# <<Create>> BasePlayer(int,int)
+ {abstract}void ability()
+ {abstract}String getName()
+ {abstract}String getAbilityLabel()
+ {abstract}AbilityType getAbilityType()
+ {abstract}String getSpritePath()
+ {abstract}BasePlayer recreate()
+ boolean isPerfectAimReady()
+ void resetAbilityEffect()
+ Image getSprite()
+ int getHp()
+ int getMaxHp()
+ void setHp(int)
+ void decreaseHp(int)
}


class attack.WindAttack {
+ {static} int COOLDOWN
+ String getName()
+ int getCooldown()
}


class attack.FireAttack {
+ {static} int COOLDOWN
+ String getName()
+ int getCooldown()
}


class game.Controller {
- BasePlayer p1
- BasePlayer p2
- boolean player1Turn
- Projectile projectile
- String projectileResult
- Attackable selectedAttack
- int burnTargetPlayer
- int burnTicksLeft
- int burnFrameTimer
+ {static} int BURN_TICKS
+ {static} int BURN_FRAMES_PER_TICK
- int frozenPlayer
- int frozenDisplayTimer
+ {static} int FROZEN_DISPLAY_FRAMES
- Map<String,int[]> cooldowns
+ {static} int WIND_TURNS
- int windTargetPlayer
- int windTurnsLeft
- int windFrameCounter
+ {static} int ABILITY_COOLDOWN
- int[] abilityCooldown
+ <<Create>> Controller(BasePlayer,BasePlayer)
+ boolean isCurrentPlayerFrozen()
+ void selectAttack(Attackable)
+ void handleSpacebar()
- void applySelectedAttack()
+ void update()
- void switchTurn()
+ void handleAbility()
- double calculatePerfectAngle()
+ double getWindXOffset(int)
+ String getSelectedAttackName()
+ AbilityType getAbilityType(boolean)
+ int getBurnTargetPlayer()
+ int getBurnTicksLeft()
+ int getBurnFrameTimer()
+ int getFrozenPlayer()
+ int getFrozenDisplayTimer()
+ Projectile getProjectile()
+ boolean isPlayer1Turn()
+ int getFireCooldown(boolean)
+ int getIceCooldown(boolean)
+ int getWindCooldown(boolean)
+ int getWindTargetPlayer()
+ int getWindTurnsLeft()
+ int getAbilityCooldown(boolean)
- int getCooldown(String,boolean)
+ String getAbilityLabel(boolean)
+ String getAndClearProjectileResult()
}




renderer.EffectRenderer +.. renderer.EffectRenderer$Particle
javafx.application.Application <|-- application.Main
attack.BaseAttack <|-- attack.NormalAttack
character.BasePlayer <|-- character.CatPlayer
character.BasePlayer <|-- character.DogPlayer
attack.BaseAttack <|-- attack.IceAttack
attack.Attackable <|.. attack.BaseAttack
attack.BaseAttack <|-- attack.WindAttack
attack.BaseAttack <|-- attack.FireAttack
@enduml